
% Linearize temporally the coherences

% Script generated by Brainstorm (17-Apr-2019)
% Input files

folder = 'Z:/brainstorm_db/Remapping_Attention_Probe/data/';


sFiles = {...
%     'Brazilian/@intra/timefreq_connectn_cohere_190419_1503.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1504.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1505.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1506.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1507.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1508.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1509.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1510.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1511.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1512.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1513.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1514.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1515.mat', ...
    'Brazilian/@intra/timefreq_connectn_cohere_190419_1516.mat'};


% Import just one file to initialize the size of the matrices
a = load([folder sFiles{1}]);
a.TF = process_compress_sym('Expand', a.TF, length(a.RowNames));


final = zeros(size(a.TF,1), length(sFiles), size(a.TF,3));

time = zeros(1,length(sFiles)); % This will hold the middle of each time-segment
time_label = cell(1,length(sFiles));

for iFile = 1:length(sFiles)
    all(iFile).coherence_file = load([folder sFiles{iFile}]);
    
    % Get connectivity matrix
%     qqqq.TF = process_compress_sym('Expand', qqqq.TF, length(qqqq.RowNames));
    all(iFile).coherence_file.TF = process_compress_sym('Expand', all(iFile).coherence_file.TF, length(all(iFile).coherence_file.RowNames));
    
    time(iFile) = mean(all(iFile).coherence_file.Time);
    time_label{iFile} = ['[' num2str(all(iFile).coherence_file.Time(1)) ' : ' num2str(all(iFile).coherence_file.Time(2)) ']'];
    
    final(:,iFile,:) = all(iFile).coherence_file.TF;
    
end


freqs = all(1).coherence_file.Freqs;

all_labels = repmat(struct('Label',[]),length(all(1).coherence_file.RowNames) * length(all(1).coherence_file.RowNames),1);


index = 0;
for iCombination = 1:length(all(1).coherence_file.RowNames)
    for jCombination = 1:length(all(1).coherence_file.RowNames)
        index = index+1;
        all_labels(index).Label = [all(1).coherence_file.RowNames{iCombination} ' x ' all(1).coherence_file.RowNames{jCombination}];
    end
end


%%

figure(1);


freqs_to_present = 2:11; % 9.3 - 51 Hz


for iCombination_selection = 1:length(all_labels)
imagesc(time, freqs(freqs_to_present), squeeze(final(iCombination_selection,:,freqs_to_present))'); set(gca,'YDir','normal'); title ([num2str(iCombination_selection) ': ' all_labels(iCombination_selection).Label]); 
colorbar; set(gca,'Xtick',time, 'Xticklabel',time_label); xlabel ('Time segment (ms)'); ylabel 'Frequency (Hz)'
waitforbuttonpress

end



























